### ISSUE TITLE
some issue about model performance

### ISSUE THREAD

**Issue by chenywu** [GestaltCogTeam/BasicTS#100]
The models trained in this repository perform much better than the models trained in other repositories. For example, Graph Wavenet in this repository has a mae of 14.65 on the PEMS08 dataset, while Graph Wavenet in another repository has a mae of 18.28 on the PEMS08 dataset. what have you done to improve the accuracy?

**Comment by zezhishao** [comment]
You can refer to our paper to find the reasons for inconsistent performance.
[Exploring Progress in Multivariate Time Series Forecasting: Comprehensive Benchmarking and Heterogeneity Analysis](https://arxiv.org/pdf/2310.06119.pdf).
