### ISSUE TITLE
怎么快速的修改输入输出长度，完成不同实验？

### ISSUE THREAD

**Issue by youxiaotu** [GestaltCogTeam/BasicTS#130]
您好，目前我观察到修改输入输出长度，需要在数据生成的时候修改。但不知道模型的初始化参数以及runner中是否也要做出相应修改？是否考虑一个快速统一修改全局的输入输出长度的接口？

**Comment by zezhishao** [comment]
输入输出长度在 Runner 中也需要进行修改，例如`CFG.DATASET_INPUT_LEN`和`wCFG.DATASET_OUTPUT_LEN`以及模型里面的参数等。目前没有一个快速地修改全局输入输出长度的接口。

**Comment by zezhishao** [comment]
您好，新版的BasicTS已经支持该项功能。
