### ISSUE TITLE
关于给模型增加额外输入的问题

### ISSUE THREAD

**Issue by sugar-hub** [GestaltCogTeam/BasicTS#133]
作者您好！十分感谢您做了这个项目，收录了这么多的模型并做了数据集适配。

我想给其中一个模型增加一个额外的输入，试着看一下效果。但是我不知道哪些接口需要做出调整。我找了很久都没找到，期待作者的回复！

**Comment by zezhishao** [comment]
增加额外的输入指的是什么呢？
