### ISSUE TITLE
预测结果可视化时，results为空

### ISSUE THREAD

**Issue by hhpu** [GestaltCogTeam/BasicTS#135]
作者您好，在pred_visualization.ipynb文件中，运行结果报错，显示 runner.test()的返回值results 为空，以至于下面plot预测结果和真实值无法进行，我是在win下运行的，请问下有没有好的解决方法？期待您的回复。

**Comment by zezhishao** [comment]
您可以参考新的预测可视化脚本，现在增强了它的易用性。
