### ISSUE TITLE
关于Embeddng可视化的问题

### ISSUE THREAD

**Issue by ggrrww** [GestaltCogTeam/BasicTS#140]
您好，我想问一下如果我想对训练好的embedding，例如STID训好的Identity matrix进行可视化，有么有什么方便的地方进行调用或者输出呢，谢谢！

**Comment by zezhishao** [comment]
STID使用T-SNE进行可视化，您可以在这里找到它的使用教程：https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

**Comment by ggrrww** [comment]
好的，谢谢您，我可以再问一下PEMS的四个数据集中csv文件中的distance是否都是没经过处理（eg.归一化，exp）的原距离呢，因为PEMS04的csv文件中distance的距离是300多，但是PEMS03的csv文件只有1左右，所以有点疑惑，但是网上也没有查到相关的资料

**Comment by zezhishao** [comment]
这个文件是这几个数据集自带的哈，可以去查询发布论文的描述
