### ISSUE TITLE
结果 

### ISSUE THREAD

**Issue by SwdandZy** [GestaltCogTeam/BasicTS#146]
您好，模型运行每次结果都不一样，有好有坏请问这是正常的吗？？非常感谢

**Comment by zezhishao** [comment]
如何复现，具体结果是？

**Comment by zezhishao** [comment]
您可以通过设定种子来确保可复现。在config中加入下面的内容：

```python
CFG.ENV = EasyDict() # 环境设置。
# GPU 和随机种子设置
CFG.ENV.SEED = 42 # 随机种子。
CFG.ENV.DETERMINISTIC = True # 是否设置随机种子以获得确定性的结果。
CFG.ENV.CUDNN = EasyDict()
CFG.ENV.CUDNN.DETERMINISTIC = True # 是否将 cuDNN 设置为确定性模式。默认值：False
```

**Comment by SwdandZy** [comment]
好的，非常感谢，我还有一个小问题想请教，如果我想获取类似您论文中的Speed结果，应该如何设置呢？
<img width="430" alt="speed" src="https://github.com/user-attachments/assets/c0010de7-5d59-44d1-9099-0cf43a8012e6">

**Comment by zezhishao** [comment]
你值得是如何复现出这些数值，还是如何计算WAPE这些指标？

**Comment by SwdandZy** [comment]
模型运行后如何找到Param和Speed这两个数值

**Comment by zezhishao** [comment]
Param在日志文件中有记录，您可以搜索：`Number of parameter`，训练时间写个脚本获取`train_time`并平均一下即可。

**Comment by SwdandZy** [comment]
好的，非常感谢
