### ISSUE TITLE
GMAN

### ISSUE THREAD

**Issue by JFz0419** [GestaltCogTeam/BasicTS#151]
后续会在baseline里加入GMAN吗

**Comment by zezhishao** [comment]
GMAN没有官方的PyTorch实现，第三方的实现效果都达不到论文中的数值，所以目前还没法加进来

**Comment by JFz0419** [comment]
okay，谢谢老哥

**Comment by JFz0419** [comment]
> GMAN没有官方的PyTorch实现，第三方的实现效果都达不到论文中的数值，所以目前还没法加进来

okay，谢谢老哥
