### ISSUE TITLE
Add STD-MAE

### ISSUE THREAD

**Issue by malay-gaherwar** [GestaltCogTeam/BasicTS#157]
Can you please add STD-MAE?
https://github.com/Jimmy-7664/STD-MAE
https://arxiv.org/abs/2312.00516

**Comment by zezhishao** [comment]
Yes, STD-MAE is the next baseline model. I am adding it.

**Comment by zezhishao** [comment]
Hi, the STD-MAE has been added. Enjoy!
If BasicTS does help you, please give us a star and consider citing this [paper](https://arxiv.org/abs/2310.06119):

```LaTeX
@article{shao2023exploring,
   title={Exploring Progress in Multivariate Time Series Forecasting: Comprehensive Benchmarking and Heterogeneity Analysis},
   author={Shao, Zezhi and Wang, Fei and Xu, Yongjun and Wei, Wei and Yu, Chengqing and Zhang, Zhao and Yao, Di and Jin, Guangyin and Cao, Xin and Cong, Gao and others},
   journal={arXiv preprint arXiv:2310.06119},
   year={2023}
 }
```
Thanks a lot!
