### ISSUE TITLE
参数调整

### ISSUE THREAD

**Issue by biubiuer** [GestaltCogTeam/BasicTS#170]
我用baseline运行我自己的数据集，需要调整参数的话，比如我要尝试加dropout，除了在模型arch上加以外，还能在哪修改呢

**Comment by zezhishao** [comment]
您指的是修改什么？如果是给模型结构加入dropout，那您需要修改baseline的实现；如果是要修改输入参数，可以在直接修改配置文件中的`CFG.MODEL.PARAM`。

**Comment by biubiuer** [comment]
> 您指的是修改什么？如果是给模型结构加入dropout，那您需要修改baseline的实现；如果是要修改输入参数，可以在直接修改配置文件中的`CFG.MODEL.PARAM`。

肯定是不改模型最好啦，可以通过往CFG.MODEL.PARAM里增加参数实现dropout吗？可以详细说下嘛？

**Comment by zezhishao** [comment]
你可以通过CFG文件控制模型参数，但不能生成模型，所以还是得实现好自己的模型结构。
