### ISSUE TITLE
How to visualize the predicted and true values?

### ISSUE THREAD

**Issue by Kylinghu** [GestaltCogTeam/BasicTS#186]
When I'm done training and testing, how do I restore the predicted value from the test_results.npz file and draw a comparison graph?

**Comment by Kylinghu** [comment]
我想直接得到预测值和真实值的数据文件，test_results.npz直接查看里面的内容好像不对该怎么办

**Comment by zezhishao** [comment]
数据文件指的是什么？

**Comment by Kylinghu** [comment]
csv文件这种，我只想得到数据集中预测目标那一列的预测值

**Comment by zezhishao** [comment]
在[这个](https://github.com/GestaltCogTeam/BasicTS/blob/master/scripts/data_visualization/pred_visualization.ipynb)脚本中：

```python
prediction = test_results['prediction'] # B, L, N, C
target = test_results['target'] # B, L, N, C
inputs = test_results['inputs'] # B, L, N, C
```
这些数据应该就可以满足你的要求了吧，N代表时间序列的数量，如果你想要取某一列的话，直接取走即可。

**Comment by zezhishao** [comment]
时间序列预测的样本是使用一个滑窗取出的，因此预测结果只会保留每个样本（即一个窗口内的数据）的结果。
如果你想要画出覆盖相当长一段时间的预测结果，而不是一个样本的预测结果，你需要根据你的实际情况选择样本进行组合。由于Test Dataloader通常是不shuffle的，这意味着样本在B这个维度上是按照时间顺序排列的，所以你可以在B这个维度上进行采样。
