### ISSUE TITLE
如何使用测试命令。

### ISSUE THREAD

**Issue by ContinualGoing** [GestaltCogTeam/BasicTS#68]

**Comment by ContinualGoing** [comment]
您好，非常感激您的贡献。
我注意到下载数据的时候提供了checkpoints，这可能包含一些最佳的参数，请问有具体的使用说明吗，我该如何使用这些参数，直接做出预测（test）
感激不尽

**Comment by zezhishao** [comment]
您好，使用训练好的模型推理的脚本可以在inference/inference.py文件中找到，直接运行即可。
运行该文件需要指定两个参数：
- 配置文件。
- 需要加载的模型参数。
您看一下脚本应该就明白了。

另外，我好像还没有公开checkpoints？（我也记不清了）
近期我正在整理实验结果，并收集checkpoints。最近两三天应该就会更新到仓库中。

**Comment by GUIsang6** [comment]
您好，我把结果运行出来后得到了checkpoints，里面的结果文件STGCN_best_val_MAE.pt，我不知道怎么查看这个内容，inference.py我运行出来报错，很多数据路径不对。希望能尽快得到你的答复，谢谢作者！
![image](https://github.com/zezhishao/BasicTS/assets/96170425/b54c004c-0082-4302-982a-e6e671d87c01)
![image](https://github.com/zezhishao/BasicTS/assets/96170425/7c1910bf-5213-4978-896f-13caec20238d)
![image](https://github.com/zezhishao/BasicTS/assets/96170425/849336f0-0840-4fdc-bc4c-5f88079e1e17)

**Comment by zezhishao** [comment]
你是如何运行的inference.py？我无法复现这个错误，请提供更多的信息。
