### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by nchesk** [GestaltCogTeam/BasicTS#75]
Hi!

Thank you for this awesome work!

Could you help me navigate on how I can use this on my custom dataset?

Thanks!

**Comment by StephenRogers1** [comment]
I also have this question

**Comment by zezhishao** [comment]
Sorry for the late reply. Currently, you can use `scripts/data_preparation/${dataset_name}/generate_training_data.py` as an example. All datasets follow similar pre-processing steps.
In addition, I am collecting `How-Tos` topics in issue #94 and try my best to provide practical tutorials. If you have more questions, even if they are very detailed, you can continue the discussion here or under issue #94.

**Comment by zezhishao** [comment]
The new version of BasicTS already supports flexible definition of datasets. You can view the documentation [here](https://github.com/GestaltCogTeam/BasicTS/blob/master/tutorial/dataset_design.md).
