### ISSUE TITLE
关于easytorch问题

### ISSUE THREAD

**Issue by Michael-D-666** [GestaltCogTeam/BasicTS#81]
我安装好环境之后使用`torch.cuda.isavailable()`确认gpu环境安装成功，但在train过程中，easytorch还是找不到gpu。麻烦请教一下是为什么
![image](https://github.com/zezhishao/BasicTS/assets/77760732/2ed53285-cf62-43aa-aa0b-f1a0a840bd05)

**Comment by zezhishao** [comment]
应该是您的[gpu编号](https://github.com/zezhishao/BasicTS/blob/7c0715ac349cf818f4e1b347ae3b5c392fe3336d/experiments/train.py#L20C5-L20C74)没有修改。

**Comment by Michael-D-666** [comment]
在 Linux环境中我发现没有任何问题，但在windows下似乎无法运行。不是到是不是个bug

**Comment by zezhishao** [comment]
gpu编号相同的情况下，这个错误只在Windows上出现吗？

**Comment by Michael-D-666** [comment]
是的，我没有修改任何文件内容，两者都按照readme中的操作下来，windows下就出现了这个问题，linux可以很顺利运行

**Comment by zezhishao** [comment]
Windows电脑上对应编号的GPU是存在的吗？假如存在的话，估计就是Windows问题了。

**Comment by shl20000110** [comment]
请问这个问题您解决了吗？我也遇到相同的问题，是不是只能在Linux系统上进行训练？

**Comment by Michael-D-666** [comment]
我发现在windows上不能--gpus ‘0’，而是应该直接 --gpus 0 。使用后这之后能在windows上成功运行

**Comment by studentlyh** [comment]
> 我发现在windows上不能--gpus '0'，而是应该直接 --gpus 0 。使用后这之后能在windows上成功运行
您好，请问Window系统识别GPU设备的解决方法找到了吗，我在Window系统下也遇到了相关问题

**Comment by Michael-D-666** [comment]
> > 我发现在windows上不能--gpus '0'，而是应该直接 --gpus 0 。使用后这之后能在windows上成功运行
> > 您好，请问Window系统识别GPU设备的解决方法找到了吗，我在Window系统下也遇到了相关问题

按照之前描述的方法也不行吗

**Comment by studentlyh** [comment]
> > > 我发现在windows上不能--gpus '0'，而是应该直接 --gpus 0 。使用后这之后能在windows上成功运行
> > > 您好，请问Window系统识别GPU设备的解决方法找到了吗，我在Window系统下也遇到了相关问题
> 
> 按照之前描述的方法也不行吗
![278305760-2ed53285-cf62-43aa-aa0b-f1a0a840bd05](https://github.com/user-attachments/assets/82ad3308-d642-4cc8-b617-b3a10c5a2e9c)


谢谢您的回复，这个问题我还有点不太确定，在某些模型上可以直接使用GPU运算，但在某些模型上会报错（但看CUDA使用率也确实在使用GPU），待我再测试一下。
