### ISSUE TITLE
如何保存预测结果

### ISSUE THREAD

**Issue by lingy-qd** [GestaltCogTeam/BasicTS#93]
您好，请问如何将预测结果和真实值保存在npy文件中？我不太熟悉easytorch框架，请提供给我一些信息，谢谢！

**Comment by zezhishao** [comment]
You can save the prediction values of the `test dataset` by modifying [test function](https://github.com/zezhishao/BasicTS/blob/34d4502dde27aba27a8961da4668c045e7ddd32e/basicts/runners/base_tsf_runner.py#L369) in runners.base_tsf_runner.py. You can save the `prediction` and `real_value` before [this line](https://github.com/zezhishao/BasicTS/blob/34d4502dde27aba27a8961da4668c045e7ddd32e/basicts/runners/base_tsf_runner.py#L391C38-L391C38).

**Comment by zezhishao** [comment]
您好，目前BasicTS已经可以自动保存预测结果，每次训练完成后，BasicTS使用最好的checkpoint进行推理，推理结果保存在test_results.npz中。
